title: 有志の会
description: 大学の制度変更に関する情報整理と経緯の記録
lang: ja-JP
timezone: Asia/Tokyo

theme: minima

header_pages:
  - system.md
  - timeline.md
  - updates.md
  - resources.md
  - participate.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
